In [12]:
import json

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

In [2]:
base_dir = '../output/'

In [3]:
df = pd.read_csv(f'{base_dir}df.csv')
df.shape

(47282, 15)

In [4]:
replacements = {}

with open(f'{base_dir}replacements.json', encoding='utf-8') as f:
    replacements = json.load(f)

In [5]:
df['key_skill_name'] = df['key_skill_name'].apply(lambda key_skill_name: replacements.get(key_skill_name, key_skill_name))

In [6]:
value_counts = df['key_skill_name'].value_counts()

In [7]:
valid_values = value_counts[value_counts >= 5].index

In [8]:
df = df[df['key_skill_name'].isin(valid_values)].reset_index(drop=True)
df.shape

(42819, 15)

In [9]:
df

,professional_role_name,key_skill_name,vacancy_employer_name,vacancy_employer_trusted,vacancy_employer_it_accredited,vacancy_salary_from,vacancy_salary_to,vacancy_salary_currency,vacancy_salary_gross,vacancy_experience_from,vacancy_experience_to,vacancy_employment_name,vacancy_schedule_name,vacancy_search_text,vacancy_area
0,"Программист, разработчик",PostgreSQL,ИнфраМенеджер,t,f,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
1,"Программист, разработчик",C#,ИнфраМенеджер,t,f,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
2,"Программист, разработчик",.NET 6,ИнфраМенеджер,t,f,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
3,"Программист, разработчик",EF Core,ИнфраМенеджер,t,f,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
4,"Программист, разработчик",MS SQL,ИнфраМенеджер,t,f,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42814,Руководитель группы разработки,Swagger,Aurora AL Nuanu,t,f,2000.0,4000.0,USD,f,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва
42815,Руководитель группы разработки,API,Aurora AL Nuanu,t,f,2000.0,4000.0,USD,f,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва
42816,Руководитель группы разработки,CI/CD,Aurora AL Nuanu,t,f,2000.0,4000.0,USD,f,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва
42817,Руководитель группы разработки,Nginx,Aurora AL Nuanu,t,f,2000.0,4000.0,USD,f,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва
42818,Руководитель группы разработки,ML,Aurora AL Nuanu,t,f,2000.0,4000.0,USD,f,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва

In [10]:
df.replace({'t': 1, 'f': 0}, inplace=True)
df

C:\Users\Grisha\AppData\Local\Temp\ipykernel_1340\514592633.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'t': 1, 'f': 0}, inplace=True)

,professional_role_name,key_skill_name,vacancy_employer_name,vacancy_employer_trusted,vacancy_employer_it_accredited,vacancy_salary_from,vacancy_salary_to,vacancy_salary_currency,vacancy_salary_gross,vacancy_experience_from,vacancy_experience_to,vacancy_employment_name,vacancy_schedule_name,vacancy_search_text,vacancy_area
0,"Программист, разработчик",PostgreSQL,ИнфраМенеджер,1,0.0,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
1,"Программист, разработчик",C#,ИнфраМенеджер,1,0.0,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
2,"Программист, разработчик",.NET 6,ИнфраМенеджер,1,0.0,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
3,"Программист, разработчик",EF Core,ИнфраМенеджер,1,0.0,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
4,"Программист, разработчик",MS SQL,ИнфраМенеджер,1,0.0,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42814,Руководитель группы разработки,Swagger,Aurora AL Nuanu,1,0.0,2000.0,4000.0,USD,0.0,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва
42815,Руководитель группы разработки,API,Aurora AL Nuanu,1,0.0,2000.0,4000.0,USD,0.0,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва
42816,Руководитель группы разработки,CI/CD,Aurora AL Nuanu,1,0.0,2000.0,4000.0,USD,0.0,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва
42817,Руководитель группы разработки,Nginx,Aurora AL Nuanu,1,0.0,2000.0,4000.0,USD,0.0,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва
42818,Руководитель группы разработки,ML,Aurora AL Nuanu,1,0.0,2000.0,4000.0,USD,0.0,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва

In [11]:
df = df.dropna().reset_index(drop=True)
df

,professional_role_name,key_skill_name,vacancy_employer_name,vacancy_employer_trusted,vacancy_employer_it_accredited,vacancy_salary_from,vacancy_salary_to,vacancy_salary_currency,vacancy_salary_gross,vacancy_experience_from,vacancy_experience_to,vacancy_employment_name,vacancy_schedule_name,vacancy_search_text,vacancy_area
0,"Программист, разработчик",HTML,ГК АВТОРУСЬ,1,0.0,300000.0,400000.0,RUR,0.0,1,3.0,Полная занятость,Полный день,Backend-разработчик,Москва
1,"Программист, разработчик",PHP,ГК АВТОРУСЬ,1,0.0,300000.0,400000.0,RUR,0.0,1,3.0,Полная занятость,Полный день,Backend-разработчик,Москва
2,"Программист, разработчик",REST,ГК АВТОРУСЬ,1,0.0,300000.0,400000.0,RUR,0.0,1,3.0,Полная занятость,Полный день,Backend-разработчик,Москва
3,"Программист, разработчик",PHP,ГК АВТОРУСЬ,1,0.0,300000.0,400000.0,RUR,0.0,1,3.0,Полная занятость,Полный день,Backend-разработчик,Москва
4,"Программист, разработчик",React,ГК АВТОРУСЬ,1,0.0,300000.0,400000.0,RUR,0.0,1,3.0,Полная занятость,Полный день,Backend-разработчик,Москва
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7726,"Программист, разработчик",Обучение и развитие,СИР ТЕХНОЛОГИИ,1,1.0,130000.0,150000.0,RUR,0.0,3,6.0,Полная занятость,Полный день,Fullstack-разработчик,Санкт-Петербург
7727,"Программист, разработчик",Управление командой,СИР ТЕХНОЛОГИИ,1,1.0,130000.0,150000.0,RUR,0.0,3,6.0,Полная занятость,Полный день,Fullstack-разработчик,Санкт-Петербург
7728,"Программист, разработчик",Ведение переговоров,СИР ТЕХНОЛОГИИ,1,1.0,130000.0,150000.0,RUR,0.0,3,6.0,Полная занятость,Полный день,Fullstack-разработчик,Санкт-Петербург
7729,"Программист, разработчик",Управление проектами,СИР ТЕХНОЛОГИИ,1,1.0,130000.0,150000.0,RUR,0.0,3,6.0,Полная занятость,Полный день,Fullstack-разработчик,Санкт-Петербург
7730,"Программист, разработчик",Организаторские навыки,СИР ТЕХНОЛОГИИ,1,1.0,130000.0,150000.0,RUR,0.0,3,6.0,Полная занятость,Полный день,Fullstack-разработчик,Санкт-Петербург

In [ ]:
numerical_data = df.select_dtypes(include=['number'])
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(numerical_data)

NameError: name 'StandardScaler' is not defined