In [1]:
import json

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

In [2]:
base_dir = '../'

In [ ]:
file_name = 'df_mini'
df = pd.read_csv(f'{base_dir}/output/{file_name}.csv')
df.shape

(8598, 6)

In [4]:
replacements = {}

with open(f'{base_dir}/output/replacements.json', encoding='utf-8') as f:
    replacements = json.load(f)

In [5]:
df['key_skill_name'] = df['key_skill_name'].apply(lambda key_skill_name: replacements.get(key_skill_name, key_skill_name))

In [ ]:
df.to_csv(f'{base_dir}/output/{file_name}_replaced.csv')

In [ ]:
# value_counts = df['key_skill_name'].value_counts()

In [ ]:
# valid_values = value_counts[value_counts >= 5].index

In [ ]:
# df = df[df['key_skill_name'].isin(valid_values)].reset_index(drop=True)
# df.shape

(42819, 15)

In [ ]:
# df

,professional_role_name,key_skill_name,vacancy_employer_name,vacancy_employer_trusted,vacancy_employer_it_accredited,vacancy_salary_from,vacancy_salary_to,vacancy_salary_currency,vacancy_salary_gross,vacancy_experience_from,vacancy_experience_to,vacancy_employment_name,vacancy_schedule_name,vacancy_search_text,vacancy_area
0,"Программист, разработчик",PostgreSQL,ИнфраМенеджер,t,f,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
1,"Программист, разработчик",C#,ИнфраМенеджер,t,f,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
2,"Программист, разработчик",.NET 6,ИнфраМенеджер,t,f,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
3,"Программист, разработчик",EF Core,ИнфраМенеджер,t,f,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
4,"Программист, разработчик",MS SQL,ИнфраМенеджер,t,f,NaN,NaN,NaN,NaN,1,3.0,Полная занятость,Удаленная работа,Backend-разработчик,Москва
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42814,Руководитель группы разработки,Swagger,Aurora AL Nuanu,t,f,2000.0,4000.0,USD,f,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва
42815,Руководитель группы разработки,API,Aurora AL Nuanu,t,f,2000.0,4000.0,USD,f,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва
42816,Руководитель группы разработки,CI/CD,Aurora AL Nuanu,t,f,2000.0,4000.0,USD,f,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва
42817,Руководитель группы разработки,Nginx,Aurora AL Nuanu,t,f,2000.0,4000.0,USD,f,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва
42818,Руководитель группы разработки,ML,Aurora AL Nuanu,t,f,2000.0,4000.0,USD,f,6,NaN,Полная занятость,Удаленная работа,Fullstack-разработчик,Москва